services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      TZ: "Europe/Warsaw"
    logging:
      options:
        max-size: 10m
    networks:
      - coyote

  php:
    image: 4programmers/php-node:8.4.2
    environment:
      - ENABLE_XDEBUG=$ENABLE_XDEBUG
      - XDEBUG_HOST=$XDEBUG_HOST
      - XDEBUG_PORT=$XDEBUG_PORT
    volumes:
      - ./:/var/www
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/" ]
      interval: 5s
      timeout: 10s
      retries: 3
    logging:
      options:
        max-size: 10m
    networks:
      - coyote

  cron:
    image: 4programmers/php-node:8.4.2
    user: nginx
    volumes:
      - ./:/var/www
    entrypoint: cron -f -l 8
    logging:
      options:
        max-size: 10m
    networks:
      - coyote

  nginx:
    image: nginx:1.17
    ports:
      - 8880:80
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - php
    logging:
      options:
        max-size: 10m
    networks:
      - coyote

  redis:
    image: redis:6-alpine
    command: redis-server --appendonly no --save
    logging:
      options:
        max-size: 10m
    networks:
      - coyote

  elasticsearch:
    image: elasticsearch:6.8.6
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    logging:
      options:
        max-size: 10m
    networks:
      - coyote

  minio:
    image: minio/minio
    volumes:
      - minio:/data
    environment:
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
    command: server /data
    ports:
      - 39000:9000
    logging:
      options:
        max-size: 10m
    networks:
      - coyote

  mailhog:
    image: mailhog/mailhog
    logging:
      options:
        max-size: 10m
    networks:
      - coyote

  selenium:
    image: selenium/standalone-chrome:3.141.59
    depends_on:
      - nginx
    volumes:
      - /dev/shm:/dev/shm
    logging:
      options:
        max-size: 10m
    networks:
      - coyote

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        mc config host add minio http://minio:9000 minio minio123 --api s3v4;
        mc mb minio/public;
        mc mb minio/local;
        mc anonymous set public minio/public;
        exit 0;
      "
    logging:
      options:
        max-size: 10m
    networks:
      - coyote

  es:
    image: 4programmers/coyote-es:1.2.1
    tty: true
    networks:
      - coyote
    logging:
      options:
        max-size: 10m
    environment:
      PORT: 3500
      APP_KEY: $APP_KEY
      ELASTICSEARCH_HOST: $ELASTICSEARCH_HOST
      INDEX: $ELASTICSEARCH_INDEX

  websocket:
    image: 4programmers/websocket:latest
    tty: true
    networks:
      - coyote
    ports:
      - 8888:8888
    logging:
      options:
        max-size: 10m
    environment:
      PORT: 8888
      REDIS_HOST: $REDIS_HOST
      APP_KEY: $APP_KEY

volumes:
  postgres:
  elasticsearch:
  minio:
  mongo:
  graylog:

networks:
  coyote:
    name: coyote

