version: '3.5'

services:
  db:
    image: postgres:11-alpine
    volumes:
      - postgres:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: coyote
      POSTGRES_PASSWORD: coyote
      POSTGRES_DB: coyote
      TZ: "Europe/Warsaw"
    logging:
      options:
        max-size: 10m
    networks:
      - coyote

  php:
    image: 4programmers/php-node:latest
    working_dir: /var/www
    environment:
      - ENABLE_XDEBUG=$ENABLE_XDEBUG
      - XDEBUG_HOST=$XDEBUG_HOST
      - XDEBUG_PORT=$XDEBUG_PORT
    volumes:
      - ./:/var/www
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/" ]
      interval: 5s
      timeout: 10s
      retries: 3
    logging:
      options:
        max-size: 10m
    networks:
      - coyote

  cron:
    image: 4programmers/php-node:latest
    working_dir: /var/www
    volumes:
      - ./:/var/www
    entrypoint: crond -f -l 8
    logging:
      options:
        max-size: 10m
    networks:
      - coyote

  nginx:
    image: nginx:1.17
    ports:
      - 8880:80
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - php
    logging:
      options:
        max-size: 10m
    networks:
      - coyote

  redis:
    image: redis:5
    command: redis-server --appendonly no --save
    logging:
      options:
        max-size: 10m
    networks:
      - coyote

  elasticsearch:
    image: elasticsearch:6.8.6
    volumes:
        - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    logging:
      options:
        max-size: 10m
    networks:
      - coyote

  minio:
    image: minio/minio
    volumes:
      - minio:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    ports:
      - 39000:9000
    logging:
      options:
        max-size: 10m
    networks:
      - coyote

  mailhog:
    image: mailhog/mailhog
    logging:
      options:
        max-size: 10m
    networks:
      - coyote

  selenium:
    image: selenium/standalone-chrome:3.11.0-antimony
    depends_on:
      - nginx
    volumes:
      - /dev/shm:/dev/shm
    logging:
      options:
        max-size: 10m
    networks:
      - coyote

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:9000 minio minio123 --api s3v4;
      /usr/bin/mc mb minio/public;
      /usr/bin/mc mb minio/local;
      /usr/bin/mc policy set public minio/public;
      exit 0;
      "
    logging:
      options:
        max-size: 10m
    networks:
      - coyote

volumes:
  postgres:
  elasticsearch:
  minio:
  mongo:
  graylog:

networks:
  coyote:
    name: coyote

