services:
  php:
    environment:
      STRIPE_KEY: $STRIPE_KEY
      STRIPE_SECRET: $STRIPE_SECRET
      STRIPE_ENDPOINT_SECRET: $STRIPE_ENDPOINT_SECRET
      GOOGLE_MAPS_KEY: $GOOGLE_MAPS_KEY
      AWS_URL: $AWS_URL
      ACCEPTANCE_TEST: production

  db:
    ports:
      - 5432:5432

  createbuckets:
    image: minio/mc:RELEASE.2020-01-03T20-33-14Z # For docker 24.0
    entrypoint: >
      /bin/sh -c "
        mc config host add minio http://minio:9000 minio minio123 --api s3v4;
        mc mb minio/public;
        mc mb minio/local;
        mc policy set download minio/public;
        exit 0;
      "
