version: '3'

tasks:
  test:
    - task: web:test
    - task: web:bundle
    - task: accept:test

includes:
  accept:
    taskfile: ./neon2/acceptance/
    dir: ./neon2/acceptance/
  web:
    taskfile: ./neon2/web/
    dir: ./neon2/web/
