version: '3'

tasks:
  webhook:listen: ngrok http http://localhost:8882/
  test:
    - task: web:test
    - task: web:bundle
    - task: accept:test

includes:
  accept:
    taskfile: ./neon2/acceptance/
    dir: ./neon2/acceptance/
  app:
    taskfile: ./neon2/app/
    dir: ./neon2/app/
  web:
    taskfile: ./neon2/web/
    dir: ./neon2/web/
