version: "3.5"
services:
  cron:
    entrypoint:
    - cron
    - -f
    - -l
    - "8"
    environment:
      API_HOST: api.4programmers.dev
      APP_DEBUG: "false"
      APP_ENV: production
      APP_KEY_FILE: /run/secrets/APP_KEY_FILE
      APP_URL: https://4programmers.dev
      AWS_ACCESS_KEY_ID_FILE: /run/secrets/AWS_ACCESS_KEY_ID_FILE
      AWS_SECRET_ACCESS_KEY_FILE: /run/secrets/AWS_SECRET_ACCESS_KEY_FILE
      AWS_URL: https://4programmers.dev/uploads/
      BROADCAST_DRIVER: redis
      DB_CONNECTION: pgsql
      DB_DATABASE: coyote
      DB_HOST: db
      DB_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD_FILE
      DB_PORT: "5432"
      DB_USERNAME: coyote
      ELASTICSEARCH_HOST: elasticsearch
      FACEBOOK_CLIENT_ID_FILE: /run/secrets/FACEBOOK_CLIENT_ID_FILE
      FACEBOOK_REDIRECT: https://4programmers.dev/OAuth/Facebook/Callback
      FACEBOOK_SECRET_ID_FILE: /run/secrets/FACEBOOK_SECRET_ID_FILE
      GITHUB_CLIENT_ID_FILE: /run/secrets/GITHUB_CLIENT_ID_FILE
      GITHUB_REDIRECT: https://4programmers.dev/OAuth/Github/Callback
      GITHUB_SECRET_ID_FILE: /run/secrets/GITHUB_SECRET_ID_FILE
      GOOGLE_CLIENT_ID_FILE: /run/secrets/GOOGLE_CLIENT_ID_FILE
      GOOGLE_MAPS_KEY_FILE: /run/secrets/GOOGLE_MAPS_KEY_FILE
      GOOGLE_REDIRECT: https://4programmers.dev/OAuth/Google/Callback
      GOOGLE_SECRET_ID_FILE: /run/secrets/GOOGLE_SECRET_ID_FILE
      LOG_CHANNEL: gelf
      MAIL_DRIVER: mailgun
      MAILGUN_DOMAIN: mg.4programmers.dev
      MAILGUN_SECRET_FILE: /run/secrets/MAILGUN_SECRET_FILE
      MINIO_ENDPOINT: http://minio:9000/
      QUEUE_DRIVER: redis
      RECAPTCHA_KEY_FILE: /run/secrets/RECAPTCHA_KEY_FILE
      RECAPTCHA_SECRET_FILE: /run/secrets/RECAPTCHA_SECRET_FILE
      REDIS_HOST: redis
      SENTRY_DSN_FILE: /run/secrets/SENTRY_DSN_FILE
      SESSION_DOMAIN: .4programmers.dev
      STRIPE_ENDPOINT_SECRET_FILE: /run/secrets/STRIPE_ENDPOINT_SECRET_FILE
      STRIPE_KEY_FILE: /run/secrets/STRIPE_KEY_FILE
      STRIPE_SECRET_FILE: /run/secrets/STRIPE_SECRET_FILE
      VAPID_PRIVATE_KEY_FILE: /run/secrets/VAPID_PRIVATE_KEY_FILE
      VAPID_PUBLIC_KEY_FILE: /run/secrets/VAPID_PUBLIC_KEY_FILE
      WS_HOST: ws.4programmers.dev
    image: 4programmers/coyote:latest
    logging:
      driver: json-file
      options:
        max-size: 10m
        tag: cron
    networks:
      coyote: null
    secrets:
    - source: APP_KEY_FILE
    - source: AWS_ACCESS_KEY_ID_FILE
    - source: AWS_SECRET_ACCESS_KEY_FILE
    - source: FACEBOOK_CLIENT_ID_FILE
    - source: FACEBOOK_SECRET_ID_FILE
    - source: GITHUB_CLIENT_ID_FILE
    - source: GITHUB_SECRET_ID_FILE
    - source: GOOGLE_CLIENT_ID_FILE
    - source: GOOGLE_MAPS_KEY_FILE
    - source: GOOGLE_SECRET_ID_FILE
    - source: MAILGUN_SECRET_FILE
    - source: POSTGRES_PASSWORD_FILE
    - source: RECAPTCHA_KEY_FILE
    - source: RECAPTCHA_SECRET_FILE
    - source: SENTRY_DSN_FILE
    - source: STRIPE_ENDPOINT_SECRET_FILE
    - source: STRIPE_KEY_FILE
    - source: STRIPE_SECRET_FILE
    - source: VAPID_PRIVATE_KEY_FILE
    - source: VAPID_PUBLIC_KEY_FILE
    volumes:
    - type: volume
      source: codebase
      target: /var/www
  db:
    command:
    - postgres
    - -c
    - config_file=/etc/postgresql/postgresql.auto.conf
    environment:
      POSTGRES_DB: coyote
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD_FILE
      POSTGRES_USER: coyote
    image: postgres:13-alpine
    logging:
      driver: json-file
      options:
        max-size: 10m
        tag: postgres
    networks:
      coyote: null
    ports:
    - mode: ingress
      target: 5432
      published: 5432
      protocol: tcp
    secrets:
    - source: POSTGRES_PASSWORD_FILE
    volumes:
    - type: bind
      source: /home/danon/Projects/coyote/docker/postgres/postgresql.prod.conf
      target: /etc/postgresql/postgresql.auto.conf
    - type: volume
      source: postgres
      target: /var/lib/postgresql/data
  elasticsearch:
    environment:
      ES_JAVA_OPTS: -Xms2g -Xmx2g
      discovery.type: single-node
    image: elasticsearch:6.8.6
    logging:
      driver: json-file
      options:
        max-size: 10m
        tag: elasticsearch
    networks:
      coyote: null
    volumes:
    - type: volume
      source: elasticsearch6
      target: /usr/share/elasticsearch/data
  es:
    environment:
      APP_KEY_FILE: /run/secrets/APP_KEY_FILE
      ELASTICSEARCH_HOST: elasticsearch
      INDEX: coyote
      PORT: "3500"
    image: 4programmers/coyote-es:1.2.1
    logging:
      driver: json-file
      options:
        max-size: 10m
        tag: node-es
    networks:
      coyote: null
    secrets:
    - source: APP_KEY_FILE
    tty: true
  fluentbit:
    image: fluent/fluent-bit:1.3-debug
    networks:
      coyote: null
    volumes:
    - type: bind
      source: /home/danon/Projects/coyote/docker/fluent-bit/fluent-bit.conf
      target: /fluent-bit/etc/fluent-bit.conf
    - type: bind
      source: /var/lib/docker/containers
      target: /var/log/containers
  graylog:
    environment:
      GRAYLOG_HTTP_EXTERNAL_URI: https://graylog.4programmers.dev/
      GRAYLOG_PASSWORD_SECRET_FILE: /run/secrets/GRAYLOG_PASSWORD_SECRET_FILE
      GRAYLOG_ROOT_PASSWORD_SHA2__FILE: /run/secrets/GRAYLOG_ROOT_PASSWORD_SHA2_FILE
    image: graylog/graylog:3.1
    networks:
      coyote: null
    ports:
    - mode: ingress
      target: 12201
      published: 12201
      protocol: tcp
    - mode: ingress
      target: 12201
      published: 12201
      protocol: udp
    secrets:
    - source: GRAYLOG_ROOT_PASSWORD_SHA2_FILE
    - source: GRAYLOG_PASSWORD_SECRET_FILE
  minio:
    command:
    - server
    - /data
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 1m0s
    environment:
      MINIO_ACCESS_KEY_FILE: AWS_ACCESS_KEY_ID_FILE
      MINIO_SECRET_KEY_FILE: AWS_SECRET_ACCESS_KEY_FILE
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:9000/minio/health/live
      timeout: 20s
      interval: 30s
      retries: 3
    image: minio/minio:RELEASE.2020-01-03T19-12-21Z
    logging:
      driver: json-file
      options:
        max-size: 10m
        tag: minio
    networks:
      coyote: null
    ports:
    - mode: ingress
      target: 9000
      published: 39000
      protocol: tcp
    secrets:
    - source: AWS_ACCESS_KEY_ID_FILE
    - source: AWS_SECRET_ACCESS_KEY_FILE
    volumes:
    - type: volume
      source: minio
      target: /data
  mongo:
    image: mongo:3
    networks:
      coyote: null
    volumes:
    - type: volume
      source: mongo
      target: /data/db
  nginx:
    image: nginx:1.17
    logging:
      driver: json-file
      options:
        max-size: 10m
        tag: nginx
    networks:
      coyote: null
    ports:
    - mode: ingress
      target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: volume
      source: codebase
      target: /var/www/
    - type: bind
      source: /home/danon/Projects/coyote/docker/nginx
      target: /etc/nginx/conf.d/
  php:
    deploy:
      replicas: 2
    environment:
      API_HOST: api.4programmers.dev
      APP_DEBUG: "false"
      APP_ENV: production
      APP_KEY_FILE: /run/secrets/APP_KEY_FILE
      APP_URL: https://4programmers.dev
      AWS_ACCESS_KEY_ID_FILE: /run/secrets/AWS_ACCESS_KEY_ID_FILE
      AWS_SECRET_ACCESS_KEY_FILE: /run/secrets/AWS_SECRET_ACCESS_KEY_FILE
      AWS_URL: https://4programmers.dev/uploads/
      BROADCAST_DRIVER: redis
      DB_CONNECTION: pgsql
      DB_DATABASE: coyote
      DB_HOST: db
      DB_MIGRATE: "true"
      DB_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD_FILE
      DB_PORT: "5432"
      DB_USERNAME: coyote
      ELASTICSEARCH_HOST: elasticsearch
      FACEBOOK_CLIENT_ID_FILE: /run/secrets/FACEBOOK_CLIENT_ID_FILE
      FACEBOOK_REDIRECT: https://4programmers.dev/OAuth/Facebook/Callback
      FACEBOOK_SECRET_ID_FILE: /run/secrets/FACEBOOK_SECRET_ID_FILE
      GITHUB_CLIENT_ID_FILE: /run/secrets/GITHUB_CLIENT_ID_FILE
      GITHUB_REDIRECT: https://4programmers.dev/OAuth/Github/Callback
      GITHUB_SECRET_ID_FILE: /run/secrets/GITHUB_SECRET_ID_FILE
      GOOGLE_CLIENT_ID_FILE: /run/secrets/GOOGLE_CLIENT_ID_FILE
      GOOGLE_MAPS_KEY_FILE: /run/secrets/GOOGLE_MAPS_KEY_FILE
      GOOGLE_REDIRECT: https://4programmers.dev/OAuth/Google/Callback
      GOOGLE_SECRET_ID_FILE: /run/secrets/GOOGLE_SECRET_ID_FILE
      LOG_CHANNEL: gelf
      MAIL_DRIVER: mailgun
      MAILGUN_DOMAIN: mg.4programmers.dev
      MAILGUN_SECRET_FILE: /run/secrets/MAILGUN_SECRET_FILE
      MINIO_ENDPOINT: http://minio:9000/
      QUEUE_DRIVER: redis
      RECAPTCHA_KEY_FILE: /run/secrets/RECAPTCHA_KEY_FILE
      RECAPTCHA_SECRET_FILE: /run/secrets/RECAPTCHA_SECRET_FILE
      REDIS_HOST: redis
      SENTRY_DSN_FILE: /run/secrets/SENTRY_DSN_FILE
      SESSION_DOMAIN: .4programmers.dev
      STRIPE_ENDPOINT_SECRET_FILE: /run/secrets/STRIPE_ENDPOINT_SECRET_FILE
      STRIPE_KEY_FILE: /run/secrets/STRIPE_KEY_FILE
      STRIPE_SECRET_FILE: /run/secrets/STRIPE_SECRET_FILE
      VAPID_PRIVATE_KEY_FILE: /run/secrets/VAPID_PRIVATE_KEY_FILE
      VAPID_PUBLIC_KEY_FILE: /run/secrets/VAPID_PUBLIC_KEY_FILE
      WS_HOST: ws.4programmers.dev
    healthcheck:
      test:
      - CMD
      - php
      - artisan
      - help
      timeout: 10s
      interval: 5s
      retries: 3
    image: 4programmers/coyote:latest
    logging:
      driver: json-file
      options:
        max-size: 10m
        tag: php
    networks:
      coyote: null
    secrets:
    - source: APP_KEY_FILE
    - source: AWS_ACCESS_KEY_ID_FILE
    - source: AWS_SECRET_ACCESS_KEY_FILE
    - source: FACEBOOK_CLIENT_ID_FILE
    - source: FACEBOOK_SECRET_ID_FILE
    - source: GITHUB_CLIENT_ID_FILE
    - source: GITHUB_SECRET_ID_FILE
    - source: GOOGLE_CLIENT_ID_FILE
    - source: GOOGLE_MAPS_KEY_FILE
    - source: GOOGLE_SECRET_ID_FILE
    - source: MAILGUN_SECRET_FILE
    - source: POSTGRES_PASSWORD_FILE
    - source: RECAPTCHA_KEY_FILE
    - source: RECAPTCHA_SECRET_FILE
    - source: SENTRY_DSN_FILE
    - source: STRIPE_ENDPOINT_SECRET_FILE
    - source: STRIPE_KEY_FILE
    - source: STRIPE_SECRET_FILE
    - source: VAPID_PRIVATE_KEY_FILE
    - source: VAPID_PUBLIC_KEY_FILE
    volumes:
    - type: volume
      source: codebase
      target: /var/www
  redis:
    command:
    - redis-server
    - --appendonly
    - "no"
    - --save
    image: redis:6-alpine
    networks:
      coyote: null
  websocket:
    environment:
      PORT: "8888"
      REDIS_HOST: redis
    image: 4programmers/websocket:latest
    logging:
      driver: json-file
      options:
        max-size: 10m
        tag: websocket
    networks:
      coyote: null
    secrets:
    - source: APP_KEY_FILE
    tty: true
  worker:
    command:
    - php
    - artisan
    - queue:work
    - --delay=5
    - --tries=3
    - --no-interaction
    - redis
    deploy:
      replicas: 2
    environment:
      API_HOST: api.4programmers.dev
      APP_DEBUG: "false"
      APP_ENV: production
      APP_KEY_FILE: /run/secrets/APP_KEY_FILE
      APP_URL: https://4programmers.dev
      AWS_ACCESS_KEY_ID_FILE: /run/secrets/AWS_ACCESS_KEY_ID_FILE
      AWS_SECRET_ACCESS_KEY_FILE: /run/secrets/AWS_SECRET_ACCESS_KEY_FILE
      AWS_URL: https://4programmers.dev/uploads/
      BROADCAST_DRIVER: redis
      DB_CONNECTION: pgsql
      DB_DATABASE: coyote
      DB_HOST: db
      DB_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD_FILE
      DB_PORT: "5432"
      DB_USERNAME: coyote
      ELASTICSEARCH_HOST: elasticsearch
      FACEBOOK_CLIENT_ID_FILE: /run/secrets/FACEBOOK_CLIENT_ID_FILE
      FACEBOOK_REDIRECT: https://4programmers.dev/OAuth/Facebook/Callback
      FACEBOOK_SECRET_ID_FILE: /run/secrets/FACEBOOK_SECRET_ID_FILE
      GITHUB_CLIENT_ID_FILE: /run/secrets/GITHUB_CLIENT_ID_FILE
      GITHUB_REDIRECT: https://4programmers.dev/OAuth/Github/Callback
      GITHUB_SECRET_ID_FILE: /run/secrets/GITHUB_SECRET_ID_FILE
      GOOGLE_CLIENT_ID_FILE: /run/secrets/GOOGLE_CLIENT_ID_FILE
      GOOGLE_MAPS_KEY_FILE: /run/secrets/GOOGLE_MAPS_KEY_FILE
      GOOGLE_REDIRECT: https://4programmers.dev/OAuth/Google/Callback
      GOOGLE_SECRET_ID_FILE: /run/secrets/GOOGLE_SECRET_ID_FILE
      LOG_CHANNEL: gelf
      MAIL_DRIVER: mailgun
      MAILGUN_DOMAIN: mg.4programmers.dev
      MAILGUN_SECRET_FILE: /run/secrets/MAILGUN_SECRET_FILE
      MINIO_ENDPOINT: http://minio:9000/
      QUEUE_DRIVER: redis
      RECAPTCHA_KEY_FILE: /run/secrets/RECAPTCHA_KEY_FILE
      RECAPTCHA_SECRET_FILE: /run/secrets/RECAPTCHA_SECRET_FILE
      REDIS_HOST: redis
      SENTRY_DSN_FILE: /run/secrets/SENTRY_DSN_FILE
      SESSION_DOMAIN: .4programmers.dev
      STRIPE_ENDPOINT_SECRET_FILE: /run/secrets/STRIPE_ENDPOINT_SECRET_FILE
      STRIPE_KEY_FILE: /run/secrets/STRIPE_KEY_FILE
      STRIPE_SECRET_FILE: /run/secrets/STRIPE_SECRET_FILE
      VAPID_PRIVATE_KEY_FILE: /run/secrets/VAPID_PRIVATE_KEY_FILE
      VAPID_PUBLIC_KEY_FILE: /run/secrets/VAPID_PUBLIC_KEY_FILE
      WS_HOST: ws.4programmers.dev
    image: 4programmers/coyote:latest
    logging:
      driver: json-file
      options:
        max-size: 10m
        tag: worker
    networks:
      coyote: null
    secrets:
    - source: APP_KEY_FILE
    - source: AWS_ACCESS_KEY_ID_FILE
    - source: AWS_SECRET_ACCESS_KEY_FILE
    - source: FACEBOOK_CLIENT_ID_FILE
    - source: FACEBOOK_SECRET_ID_FILE
    - source: GITHUB_CLIENT_ID_FILE
    - source: GITHUB_SECRET_ID_FILE
    - source: GOOGLE_CLIENT_ID_FILE
    - source: GOOGLE_MAPS_KEY_FILE
    - source: GOOGLE_SECRET_ID_FILE
    - source: MAILGUN_SECRET_FILE
    - source: POSTGRES_PASSWORD_FILE
    - source: RECAPTCHA_KEY_FILE
    - source: RECAPTCHA_SECRET_FILE
    - source: SENTRY_DSN_FILE
    - source: STRIPE_ENDPOINT_SECRET_FILE
    - source: STRIPE_KEY_FILE
    - source: STRIPE_SECRET_FILE
    - source: VAPID_PRIVATE_KEY_FILE
    - source: VAPID_PUBLIC_KEY_FILE
networks:
  coyote:
    name: coyote
volumes:
  codebase: {}
  elasticsearch6: {}
  graylog: {}
  minio: {}
  mongo: {}
  postgres: {}
secrets:
  APP_KEY_FILE:
    name: APP_KEY_FILE
    external: true
  AWS_ACCESS_KEY_ID_FILE:
    name: AWS_ACCESS_KEY_ID_FILE
    external: true
  AWS_SECRET_ACCESS_KEY_FILE:
    name: AWS_SECRET_ACCESS_KEY_FILE
    external: true
  FACEBOOK_CLIENT_ID_FILE:
    name: FACEBOOK_CLIENT_ID_FILE
    external: true
  FACEBOOK_SECRET_ID_FILE:
    name: FACEBOOK_SECRET_ID_FILE
    external: true
  GITHUB_CLIENT_ID_FILE:
    name: GITHUB_CLIENT_ID_FILE
    external: true
  GITHUB_SECRET_ID_FILE:
    name: GITHUB_SECRET_ID_FILE
    external: true
  GOOGLE_CLIENT_ID_FILE:
    name: GOOGLE_CLIENT_ID_FILE
    external: true
  GOOGLE_MAPS_KEY_FILE:
    name: GOOGLE_MAPS_KEY_FILE
    external: true
  GOOGLE_SECRET_ID_FILE:
    name: GOOGLE_SECRET_ID_FILE
    external: true
  GRAYLOG_PASSWORD_SECRET_FILE:
    name: GRAYLOG_PASSWORD_SECRET_FILE
    external: true
  GRAYLOG_ROOT_PASSWORD_SHA2_FILE:
    name: GRAYLOG_ROOT_PASSWORD_SHA2_FILE
    external: true
  MAILGUN_SECRET_FILE:
    name: MAILGUN_SECRET_FILE
    external: true
  POSTGRES_PASSWORD_FILE:
    name: POSTGRES_PASSWORD_FILE
    external: true
  RECAPTCHA_KEY_FILE:
    name: RECAPTCHA_KEY_FILE
    external: true
  RECAPTCHA_SECRET_FILE:
    name: RECAPTCHA_SECRET_FILE
    external: true
  SENTRY_DSN_FILE:
    name: SENTRY_DSN_FILE
    external: true
  STRIPE_ENDPOINT_SECRET_FILE:
    name: STRIPE_ENDPOINT_SECRET_FILE
    external: true
  STRIPE_KEY_FILE:
    name: STRIPE_KEY_FILE
    external: true
  STRIPE_SECRET_FILE:
    name: STRIPE_SECRET_FILE
    external: true
  VAPID_PRIVATE_KEY_FILE:
    name: VAPID_PRIVATE_KEY_FILE
    external: true
  VAPID_PUBLIC_KEY_FILE:
    name: VAPID_PUBLIC_KEY_FILE
    external: true
  WS_PROXY_FILE:
    name: WS_PROXY_FILE
    external: true
x-env:
  APP_DEBUG: "false"
  APP_ENV: production
  APP_KEY_FILE: /run/secrets/APP_KEY_FILE
  AWS_ACCESS_KEY_ID_FILE: /run/secrets/AWS_ACCESS_KEY_ID_FILE
  AWS_SECRET_ACCESS_KEY_FILE: /run/secrets/AWS_SECRET_ACCESS_KEY_FILE
  BROADCAST_DRIVER: redis
  DB_CONNECTION: pgsql
  DB_DATABASE: coyote
  DB_HOST: db
  DB_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD_FILE
  DB_PORT: 5432
  DB_USERNAME: coyote
  ELASTICSEARCH_HOST: elasticsearch
  FACEBOOK_CLIENT_ID_FILE: /run/secrets/FACEBOOK_CLIENT_ID_FILE
  FACEBOOK_SECRET_ID_FILE: /run/secrets/FACEBOOK_SECRET_ID_FILE
  GITHUB_CLIENT_ID_FILE: /run/secrets/GITHUB_CLIENT_ID_FILE
  GITHUB_SECRET_ID_FILE: /run/secrets/GITHUB_SECRET_ID_FILE
  GOOGLE_CLIENT_ID_FILE: /run/secrets/GOOGLE_CLIENT_ID_FILE
  GOOGLE_MAPS_KEY_FILE: /run/secrets/GOOGLE_MAPS_KEY_FILE
  GOOGLE_SECRET_ID_FILE: /run/secrets/GOOGLE_SECRET_ID_FILE
  LOG_CHANNEL: gelf
  MINIO_ENDPOINT: http://minio:9000/
  QUEUE_DRIVER: redis
  RECAPTCHA_KEY_FILE: /run/secrets/RECAPTCHA_KEY_FILE
  RECAPTCHA_SECRET_FILE: /run/secrets/RECAPTCHA_SECRET_FILE
  REDIS_HOST: redis
  SENTRY_DSN_FILE: /run/secrets/SENTRY_DSN_FILE
  STRIPE_ENDPOINT_SECRET_FILE: /run/secrets/STRIPE_ENDPOINT_SECRET_FILE
  STRIPE_KEY_FILE: /run/secrets/STRIPE_KEY_FILE
  STRIPE_SECRET_FILE: /run/secrets/STRIPE_SECRET_FILE
  VAPID_PRIVATE_KEY_FILE: /run/secrets/VAPID_PRIVATE_KEY_FILE
  VAPID_PUBLIC_KEY_FILE: /run/secrets/VAPID_PUBLIC_KEY_FILE
x-secrets:
- APP_KEY_FILE
- POSTGRES_PASSWORD_FILE
- AWS_ACCESS_KEY_ID_FILE
- AWS_SECRET_ACCESS_KEY_FILE
- SENTRY_DSN_FILE
- RECAPTCHA_KEY_FILE
- RECAPTCHA_SECRET_FILE
- GITHUB_CLIENT_ID_FILE
- GITHUB_SECRET_ID_FILE
- GOOGLE_CLIENT_ID_FILE
- GOOGLE_SECRET_ID_FILE
- GOOGLE_MAPS_KEY_FILE
- FACEBOOK_CLIENT_ID_FILE
- FACEBOOK_SECRET_ID_FILE
- STRIPE_KEY_FILE
- STRIPE_SECRET_FILE
- STRIPE_ENDPOINT_SECRET_FILE
- VAPID_PUBLIC_KEY_FILE
- VAPID_PRIVATE_KEY_FILE
