version: '3'

tasks:
  start:
    - task: app:serve
  test:
    - task: test:install
    - task: test:test

includes:
  app:
    taskfile: ./acceptance-app/
    dir: ./acceptance-app/
  test:
    taskfile: ./acceptance-test/
    dir: ./acceptance-test/
