name: Stagging

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGGING_IP }}
          username: github
          key: ${{ secrets.STAGGING_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/4programmers.dev
            git reset --hard
            git pull
            docker-compose exec -T php composer install --no-dev
            docker-compose exec -T php make install-assets
            docker-compose exec -T php make migration
            docker-compose exec -T php make assets-production
            docker-compose exec -T php make cache-config
            docker-compose exec -T php php artisan queue:restart
