name: Staging

on:
  push:
    branches: [ master, staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGGING_IP }}
          username: github
          key: ${{ secrets.STAGGING_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/4programmers.dev
            git fetch
            git reset origin/staging --hard
            git pull
            docker-compose exec -T php composer install --no-dev
            make install-assets
            make migration
            make assets-production
            make cache-config
            docker-compose exec -T php php artisan queue:restart
