name: Testing
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add user
        run: cat /etc/passwd
      #  run: sudo addgroup --gid 1000 nginx && sudo useradd --uid 1000 -g nginx nginx

      - name: Setup config
        run: cp .env.default .env

      - name: Run docker containers
        run: docker-compose build && docker-compose -f docker-compose.yaml -f docker-compose.testing.yaml up -d
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
          STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
          STRIPE_ENDPOINT_SECRET: ${{ secrets.STRIPE_ENDPOINT_SECRET }}

      - name: Show logs
        run: docker-compose -f docker-compose.yaml -f docker-compose.testing.yaml logs websocket

      - uses: actions/cache@v2
        with:
          path: '**/vendor'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/composer.lock') }}

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: docker-compose exec -T php make install

      - name: Create uploads directory
        run: mkdir public/uploads

      - name: Setup owner
        run: sudo chown -R runneradmin:runneradmin ./

      - name: Run tests
        run: docker-compose exec -T --user=nginx:nginx php php vendor/bin/phpunit

      - name: Run Dusk
        run: docker-compose exec -T --user=nginx:nginx php php artisan dusk

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs
          path: storage/logs/
          retention-days: 5

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: screenshots
          path: tests/Browser/screenshots/
          retention-days: 5

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: console
          path: tests/Browser/console/
          retention-days: 5
