name: Testing
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add user
        run: cat /etc/passwd
      #  run: sudo addgroup --gid 1000 nginx && sudo useradd --uid 1000 -g nginx nginx

      - name: Setup config
        run: cp .env.default .env

      - name: Run docker containers
        run: docker-compose build && docker-compose -f docker-compose.yaml -f docker-compose.testing.yaml up -d
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
          STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
          STRIPE_ENDPOINT_SECRET: ${{ secrets.STRIPE_ENDPOINT_SECRET }}

      - name: Show logs
        run: docker-compose logs php

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install packages
        run: docker-compose exec -T php make install

      - name: Create uploads directory
        run: mkdir public/uploads

      - name: Create uploads directory
        run: sudo chown -R runneradmin:runneradmin ./

      - name: Run tests
        run: docker-compose exec -T --user=nginx:nginx php php vendor/bin/phpunit

      - name: Run Dusk
        run: docker-compose exec -T --user=nginx:nginx php php artisan dusk

      - name: Ls log
        if: ${{ always() }}
        run: ls -lsa storage/logs

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs
          path: storage/logs/
          retention-days: 5

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: screenshots
          path: tests/Browser/screenshots/
          retention-days: 5

