name: Tests

on:
  push:
    branches: ['*']

jobs:
  unit:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/composer
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Install composer dependencies
        run: composer install --no-interaction --no-scripts --prefer-dist

      - name: Run module unit tests
        run: ./vendor/bin/phpunit ./modules/

      - name: Run acceptance tests (in-memory)
        run: TEST_CHANNEL=in-memory ./vendor/bin/behat

  integration:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - name: Setup laravel
        run: cp .env.default .env

      - name: Run docker containers
        run: docker compose -f docker-compose.yaml up -d

      - name: Setup directory owner
        run: sudo chown -R packer:packer ./ # User with UID 1000 on host machine

      - name: Install coyote server
        run: make composer-install migrate

      - name: Run Behat tests
        run: docker compose exec -T php bash -c 'TEST_CHANNEL=integration vendor/bin/behat'
